### ISSUE TITLE
Add "villager" trade tree for trades that should be added to all villagers

### ISSUE THREAD

**Issue by alfalfascout** [alfalfascout/CustomVillageTrades#8]
for example, this would add eggs for emeralds to all villagers at their first tier:

```
villager:
    tier1:
        trade1:
            result:
                material: emerald
            ingredient1:
                material: egg
```
